export const Questions = [
  {
    question: "who is a son of Maharaj Dashrath?",
    optionA: "Shree_Krushna",
    optionB: "Shree_Ram",
    optionC: "Shree_Hari",
    optionD: "Shree_Vitthal",
    answer: 2,
  },
  {
    question: "Which the following is a nick name of 'Maharj Arjun' ?",
    optionA: "Savyasachi",
    optionB: "Dharmaraj",
    optionC: "Gopal",
    optionD: "Bhisma",
    answer: 1,
  },
  {
    question: "Name of the king of the Dwaraka?",
    optionA: "Shree_Krushna",
    optionB: "Shree_Balram",
    optionC: "Shree_Dhutarashtra",
    optionD: "Shree_Ugrasen",
    answer: 4,
  },
  {
    question: "The writer of 'Shree_Mahabharat' epic?",
    optionA: "Maharshi Valmiki ji",
    optionB: "Maharshi Vyas ji",
    optionC: "Maharshi Kapil ji",
    optionD: "Maharshi Vasishtha ji",
    answer: 2,
  },
  {
    question: "The writer of 'Shree_Ramayan' epic?",
    optionA: "Maharshi Valmiki ji",
    optionB: "Maharshi Vyas ji",
    optionC: "Maharshi Kapil ji",
    optionD: "Maharshi Vasishtha ji",
    answer: 1,
  },
  {
    question: "The ancient name of 'Bharat' ?",
    optionA: "Hindustan",
    optionB: "India",
    optionC: "Aryavart/ Bharatvarsh",
    optionD: "Jambudweep",
    answer: 3,
  },
  {
    question: "the name of the sister of Shree_krushna & Shree_Balram ?",
    optionA: "Maharani Kunti",
    optionB: "Dusshala",
    optionC: "Subhadra",
    optionD: "Bhanumati",
    answer: 3,
  },
  {
    question: "the name of husband of Subhadra ?",
    optionA: "Maharaj Arjun",
    optionB: "Maharaj Duryodhan",
    optionC: "Maharaj Yudhishthir",
    optionD: "Maharaj Bhim",
    answer: 1,
  },
  {
    question: "The name of the Bhishma Pitamah?",
    optionA: "Shree_Shakuntan",
    optionB: "Shree_Vasudev",
    optionC: "Shree_Dharmaraj",
    optionD: "Shree_Devavrat",
    answer: 4,
  },
];
